---
title: "forestfires_binom"
author: "Christina Sousa"
date: "March 20, 2019"
output: html_document
---

```{r}
#data file can be obtained at https://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/
#read data into r
forest_bin <-read.csv("forestfires.csv")

#change spatial variables X and Y to factors
forest_bin$X<-as.factor(forest_bin$X)
forest_bin$Y<-as.factor(forest_bin$Y)

#add binomial area column
forest_bin2<-cbind(forest_bin[,1:12],forest_bin$area>0)
colnames(forest_bin2)[13]<-"large"
forest_bin2$large<-as.factor(forest_bin2$large)

#add categorical rain column
forest_bin3<-cbind(forest_bin2[,1:11],forest_bin2$rain>0,forest_bin2[,13])
colnames(forest_bin3)[12]<-"rain"
colnames(forest_bin3)[13]<-"large"
forest_bin3$rain<-as.factor(forest_bin3$rain)
head(forest_bin3)
```

```{r}
#add categorical weekday and season variables
week <- rep(0,length(forest_bin3$day))

week[which(forest_bin3$day == "mon")] <- 0
week[which(forest_bin3$day == "tue")] <- 0
week[which(forest_bin3$day == "wed")] <- 0
week[which(forest_bin3$day == "thu")] <- 0
week[which(forest_bin3$day == "fri")] <- 0
week[which(forest_bin3$day == "sat")] <- 1
week[which(forest_bin3$day == "sun")] <- 1

seas <- rep(0,length(forest_bin3$month), ylab = "log(area)",
     xlab = "Month",main = "Month Data")

seas[which(forest_bin3$month == "jan")] <- 0
seas[which(forest_bin3$month == "feb")] <- 0
seas[which(forest_bin3$month == "mar")] <- 0
seas[which(forest_bin3$month == "apr")] <- 1
seas[which(forest_bin3$month == "may")] <- 1
seas[which(forest_bin3$month == "jun")] <- 1
seas[which(forest_bin3$month == "jul")] <- 2
seas[which(forest_bin3$month == "aug")] <- 2
seas[which(forest_bin3$month == "sep")] <- 2
seas[which(forest_bin3$month == "oct")] <- 3
seas[which(forest_bin3$month == "nov")] <- 3
seas[which(forest_bin3$month == "dec")] <- 3

forest_bin3$week <- as.factor(week)
levels(forest_bin3$week)<-c("weekday","weekend")
forest_bin3$season <- as.factor(seas)
levels(forest_bin3$season)<-c("Winter","Spring","Summer","Fall")

head(forest_bin3)
```

```{r}
forest_bin4<-cbind(paste(forest_bin3$X,forest_bin3$Y,sep = ","),forest_bin3[,15:14], forest_bin3[,3:13])
colnames(forest_bin4)[1]<-"XY"
summary(forest_bin4)
par(mfrow=c(2,3))
plot(forest_bin4$XY, main = "Number of Fires by Park Region", ylab = "Number of Fires",
     xlab = "Spatial Coordinates")
plot(forest_bin4$season, main = "Number of Fires by Season", ylab = "Number of Fires")
plot(forest_bin4$week, main = "Number of Fires by Weekdays", ylab = "Number of Fires")

#same plots with conditional data (large fires only)
indices<-which(forest_bin4$large==T)
plot(forest_bin4$XY[indices], main = "Number of Large Fires by Park Region", ylab = "Number of Fires",
     xlab = "Spatial Coordinates")
plot(forest_bin4$season[indices], main = "Number of Large Fires by Season", ylab = "Number of Fires")
plot(forest_bin4$week[indices], main = "Number of Large Fires by Weekdays", ylab = "Number of Fires")

```

```{r, message=F, warning=F}
require(tree)
data.tree <- tree(large~., data=forest_bin4[,2:14])
plot(data.tree, type="uniform")
text(data.tree)


```

